title: Matt Dotsey # your name (or website title) here
logo: "/images/PortPic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Analyst
  <br><br>
  Welcome to My Portfolio! 
  <br><br>
  <a href="www.linkedin.com/in/mattdotsey">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
